from tkinter import *  
from tkinter import ttk
from tkinter import messagebox
  
window = Tk()  
window.title("Добро пожаловать на тест")  
window.geometry('600x450') 
tab_control = ttk.Notebook(window) 
tab1 = ttk.Frame(tab_control)  
tab2 = ttk.Frame(tab_control)
tab3 = ttk.Frame(tab_control) 
tab4 = ttk.Frame(tab_control)
tab5 = ttk.Frame(tab_control)
canvas = Canvas(window, height=300, width=250)
canvas.pack()
frame=Frame()
frame.place(relx=0.15, rely=0.15 ,height= 0.7, width=0.7)
title = Label(frame, text="G")
title.pack()
btn = Button(frame, text="Кнопка")
btn.pack()
tab_control.add(tab1, text="Первый вопрос")
tab_control.add(tab2, text='Второй вопрос')
tab_control.add(tab3, text="Третий вопрос")
tab_control.add(tab4, text="Четвёртый вопрос")
tab_control.add(tab5, text="Пятый вопрос")
lbl1 = Label(tab1, text="Линия пересечения двух сфер есть")   
lbl1.grid(column=0, row=0)  
lbl2 = Label(tab2, text='Сколько вершин у куба?')  
lbl2.grid(column=0, row=0)
lbl3 = Label(tab3, text='Какие фигуры являются телами вращения?')  
lbl3.grid(column=0, row=0)
lbl4 = Label(tab4, text='У четырехугольника, вписанного в окружность, сумма противоположных углов равна:')  
lbl4.grid(column=0, row=0)
lbl5 = Label(tab5, text='Свойства основания циллиндра:')  
lbl5.grid(column=0, row=0)
tab_control.pack(expand=1, fill='both')
window.mainloop()